# Generated by Django 4.0.6 on 2022-08-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
