# Generated by Django 4.0.6 on 2022-08-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
