# Generated by Django 4.0.6 on 2022-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favicon',
            name='url',
        ),
        migrations.AddField(
            model_name='favicon',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
