# Generated by Django 4.0.6 on 2022-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='zipped_favs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
