# Generated by Django 4.0.6 on 2022-08-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0002_favicons'),
        ('favigen', '0002_rename_favicons_favicon_remove_customuser_full_name_and_more'),
    ]

    operations = [
    ]
