# Generated by Django 4.0.6 on 2022-08-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0003_merge_20220809_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favicons',
        ),
    ]
