# Generated by Django 4.0.6 on 2022-08-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0003_remove_favicon_favicon_remove_favicon_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_favicon', to='favigen.image'),
        ),
    ]
