# Generated by Django 4.0.6 on 2022-08-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0004_alter_favicon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='favigen.image'),
        ),
    ]
