# Generated by Django 4.0.6 on 2022-08-12 00:59

from django.db import migrations, models
import favigen.models


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0005_alter_favicon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='new_file_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='old_file_name',
        ),
        migrations.AddField(
            model_name='favicon',
            name='file_byte_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favicon',
            name='file_type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='favicon',
            name='new_filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='favicon',
            name='original_filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=favigen.models.user_directory_path),
        ),
    ]
