# Generated by Django 4.0.6 on 2022-08-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favigen', '0006_remove_image_file_size_remove_image_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='file_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
